[package]
name = "BMI_calc"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.21", features = ["csr"] } # client-side rendering
wasm-bindgen = "0.2"
web-sys = "0.3.83"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"        # optional: smaller wasm
lto = true
