[package]
name = "yew_styles"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = "0.3"

[dev-dependencies]
trunk = "0.17"

